name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - uses: actions/checkout@v4
      - name: Build and push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ vars.DOCKER_USERNAME }}/myday-api-wrapper
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tag_semver: true
          buildoptions: "--pull"
